name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  buildDebug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembledebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug

  standardMobileDebug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemblestandardMobileDebug
        env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-standard-Mobile-Debug
        path: app/build/outputs/apk/standard/mobile/debug
