name: Build all variants debug

on:
  workflow_dispatch:
jobs:
  buildDebug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build all variants debug APK
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembledebug
      env:
        CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

    - name: Upload nonFreeMobile debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-nonFreeMobile-debug
        path: app/build/outputs/apk/nonFreeMobile/debug

    - name: Upload nonFreeTv debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-nonFreeTv-debug
        path: app/build/outputs/apk/nonFreeTv/debug

    - name: Upload standardMobile debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-standardMobile-debug
        path: app/build/outputs/apk/standardMobile/debug

    - name: Upload standardTv debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-standardTv-debug
        path: app/build/outputs/apk/standardTv/debug
